export default {
    user_define_food:[
        {"type":"food","foodName":"自定义","Calories":0}
        ],
    user_define_sport:[
        {"type":"sport","sportName":"自定义","Calories":0}
        ],
    user_define_drink:[
        {"type":"drink","foodName":"自定义","Calories":0}
        ],
    wugulei:[
        {"num":2,"foodName":"黑芝麻","Calories":531},
        {"num":3,"foodName":"白芝麻","Calories":517},
        {"num":5,"foodName":"方便面","Calories":472},
        {"num":7,"foodName":"油条","Calories":386},
        {"num":95,"foodName":"豆腐干","Calories":140},
        {"num":99,"foodName":"臭豆腐","Calories":130},
        {"num":100,"foodName":"北豆腐","Calories":98},
        {"num":102,"foodName":"南豆腐","Calories":57},
        {"num":103,"foodName":"豆奶","Calories":30},
        {"num":104,"foodName":"豆浆","Calories":13},
        {"num":105,"foodName":"豆腐脑","Calories":10},
        {"num":106,"foodName":"油豆腐","Calories":244}
        ],
    shucailei:[
        {"num":5,"foodName":"黄花菜","Calories":203},
        {"num":6,"foodName":"竹笋","Calories":306},
        {"num":80,"foodName":"豌豆苗","Calories":30},
        {"num":82,"foodName":"四季豆","Calories":29},
        {"num":83,"foodName":"荷兰豆","Calories":31},
        {"num":85,"foodName":"木瓜","Calories":31},
        {"num":86,"foodName":"韭菜","Calories":29},
        {"num":93,"foodName":"竹笋","Calories":20},
        {"num":94,"foodName":"西红柿","Calories":20},
        {"num":95,"foodName":"长茄子","Calories":20},
        {"num":96,"foodName":"苦瓜","Calories":23},
        {"num":98,"foodName":"西葫芦","Calories":25},
        {"num":100,"foodName":"莴笋叶","Calories":20},
        {"num":101,"foodName":"绿豆芽","Calories":18},
        {"num":103,"foodName":"黄瓜","Calories":16},
        {"num":106,"foodName":"白菜","Calories":18},
        {"num":112,"foodName":"莴笋叶","Calories":23},
        {"num":114,"foodName":"水芹","Calories":20},
        {"num":115,"foodName":"生菜","Calories":14},
        {"num":117,"foodName":"冬瓜","Calories":14},
        ],
    shuiguolei:[
        {"num":2,"foodName":"松子","Calories":2000},
        {"num":3,"foodName":"核桃","Calories":1458},
        {"num":7,"foodName":"山核桃","Calories":2504},
        {"num":9,"foodName":"榛子","Calories":2829},
        {"num":74,"foodName":"柿饼","Calories":258},
        {"num":75,"foodName":"椰子","Calories":700},
        {"num":78,"foodName":"密云小枣","Calories":233},
        {"num":130,"foodName":"西瓜","Calories":42},
        {"num":131,"foodName":"白兰瓜","Calories":38}
        ],
    roulei: [
        {"num":4,"foodName":"猪肉（肥）","Calories":816},
        {"num":2,"foodName":"羊肉干（绵羊）","Calories":588},
        {"num":3,"foodName":"腊肠","Calories":584},
        {"num":5,"foodName":"猪肉（肋条肉）","Calories":610},
        {"num":6,"foodName":"牛肉干","Calories":550 },
        {"num":9,"foodName":"香肠","Calories":508 },
        {"num":13,"foodName":"北京烤鸭","Calories":545 },
        {"num":14,"foodName":"广东香肠","Calories":433 },
        {"num":18,"foodName":"猪肉（瘦）","Calories":395 },
        {"num":26,"foodName":"猪肉（后臀尖）","Calories":341 },
        {"num":28,"foodName":"猪肉（后蹄膀）","Calories":438 },
        {"num":29,"foodName":"金华火腿","Calories":318 },
        {"num":30,"foodName":"猪肘棒（熟）","Calories":436 },
        {"num":31,"foodName":"盐水鸭（熟）","Calories":385 },
        {"num":32,"foodName":"蒜肠","Calories":297 },
        {"num":34,"foodName":"羊肉","Calories":293 },
        {"num":36,"foodName":"烧鹅","Calories":396 },
        {"num":40,"foodName":"牛舌","Calories":196 },
        {"num":41,"foodName":"鸡翅","Calories":281 },
        {"num":101,"foodName":"烤鸡","Calories":329 },
        {"num":102,"foodName":"鸭","Calories":353 },
        {"num":103,"foodName":"羊肉串","Calories":234 },
        {"num":154,"foodName":"鸡血","Calories":49 }
        ],
    danlei: [
        {"num":3,"foodName":"鸭蛋黄","Calories":378 },
        {"num":11,"foodName":"鹅蛋","Calories":225 },
        {"num":12,"foodName":"咸鸭蛋","Calories":216 },
        {"num":13,"foodName":"鸭蛋","Calories":207 },
        {"num":15,"foodName":"鸡蛋白","Calories":60 },
        {"num":16,"foodName":"鹅蛋白","Calories":48 },
        {"num":17,"foodName":"鸭蛋白","Calories":47 }
        ],
    shuichanlei: [
        {"num":4,"foodName":"鲍鱼（干）","Calories":322 },
        {"num":5,"foodName":"鱿鱼（干）","Calories":319 },
        {"num":6,"foodName":"鱼片干","Calories":303 },
        {"num":7,"foodName":"墨鱼（干）","Calories":350 },
        {"num":8,"foodName":"干贝","Calories":264 },
        {"num":9,"foodName":"海参","Calories":282 },
        {"num":11,"foodName":"海鲫鱼","Calories":343 },
        {"num":12,"foodName":"丁香鱼（干）","Calories":196 },
        {"num":51,"foodName":"鲚鱼(小凤尾鱼)","Calories":138 },
        {"num":52,"foodName":"边鱼","Calories":177 },
        {"num":53,"foodName":"沙梭鱼","Calories":169 },
        {"num":71,"foodName":"鲇鱼","Calories":157 },
        {"num":72,"foodName":"鲢鱼","Calories":167 },
        {"num":92,"foodName":"生蚝","Calories":57 },
        {"num":94,"foodName":"章鱼","Calories":52 },
        {"num":96,"foodName":"蛤蜊（花蛤）","Calories":98 },
        {"num":98,"foodName":"河蚌","Calories":157 },
        {"num":99,"foodName":"海蜇皮","Calories":33 },
        ],
    nailei: [
        {"num":2,"foodName":"奶油","Calories":720 },
        {"num":3,"foodName":"黄油渣","Calories":599 },
        {"num":5,"foodName":"羊奶粉","Calories":498 },
        {"num":6,"foodName":"牛奶粉","Calories":484 },
        {"num":8,"foodName":"炼乳","Calories":332 },
        {"num":9,"foodName":"奶酪","Calories":328 },
        {"num":11,"foodName":"酸奶","Calories":72 },
        {"num":12,"foodName":"果料酸奶","Calories":67 },
        {"num":13,"foodName":"母乳","Calories":65 },
        {"num":14,"foodName":"酸奶（中脂）","Calories":64 },
        {"num":15,"foodName":"奶片","Calories":472 },
        {"num":21,"foodName":"奶豆腐","Calories":343 },
        {"num":23,"foodName":"羊奶（鲜）","Calories":59 },
        {"num":24,"foodName":"酸奶","Calories":57 },
        {"num":25,"foodName":"牛奶","Calories":54 },
        {"num":26,"foodName":"牛奶","Calories":51 },
        {"num":28,"foodName":"果味奶","Calories":20 }
        ],
    gaodianlei: [
        {"num":2,"foodName":"曲奇饼","Calories":546 },
        {"num":5,"foodName":"麻花","Calories":524 },
        {"num":7,"foodName":"凤尾酥","Calories":511 },
        {"num":8,"foodName":"起酥","Calories":499 },
        {"num":9,"foodName":"京式黄酥","Calories":490 },
        {"num":10,"foodName":"桃酥","Calories":481 },
        {"num":12,"foodName":"福来酥","Calories":465 },
        {"num":13,"foodName":"春卷","Calories":463 },
        {"num":15,"foodName":"鹅油卷","Calories":461 },
        {"num":17,"foodName":"蛋麻脆","Calories":452 },
        {"num":18,"foodName":"开花豆","Calories":446 },
        {"num":19,"foodName":"钙奶饼干","Calories":444 },
        {"num":21,"foodName":"江米条","Calories":439 },
        {"num":22,"foodName":"面包（法式牛角）","Calories":375 },
        {"num":72,"foodName":"年糕","Calories":154 },
        {"num":78,"foodName":"小豆粥","Calories":61 },
        {"num":81,"foodName":"凉粉","Calories":37 },
        ],
    zaojunlei: [
        {"num":2 ,"foodName":"琼脂","Calories":311 },
        {"num":7 ,"foodName":"冬菇","Calories":247 },
        {"num":8 ,"foodName":"榛蘑","Calories":204 },
        {"num":9 ,"foodName":"苔菜","Calories":148 },
        {"num":10 ,"foodName":"松蘑","Calories":112 },
        {"num":18 ,"foodName":"黑木耳","Calories":205 },
        {"num":28 ,"foodName":"猴头菇（罐装）","Calories":13 }
        ],
    qita: [
        {"num":11,"foodName":"芝麻酱","Calories":618 },
        {"num":2 ,"foodName":"花生酱","Calories":594 },
        {"num":3 ,"foodName":"芥末","Calories":476 },
        {"num":4 ,"foodName":"胡椒粉","Calories":357 },
        {"num":28 ,"foodName":"辣椒糊","Calories":31 },
        {"num":29 ,"foodName":"酱萝卜","Calories":30 },
        {"num":30 ,"foodName":"榨菜","Calories":29 },
        {"num":32 ,"foodName":"酱黄瓜","Calories":24 },
        ],
    tanglei: [
        {"num":2,"foodName":"巧克力","Calories":586 },
        {"num":3 ,"foodName":"芝麻南糖","Calories":538 },
        {"num":7 ,"foodName":"麦乳精","Calories":429 },
        {"num":8 ,"foodName":"酸梅精","Calories":394 },
        {"num":9 ,"foodName":"山楂精","Calories":386 },
        {"num":11 ,"foodName":"可可粉","Calories":320 },
        {"num":14 ,"foodName":"绵白糖","Calories":396 },
        {"num":15 ,"foodName":"红糖","Calories":389 },
        {"num":16 ,"foodName":"米花糖","Calories":384 },
        ],
     'zoulupaobu': [
        {"num":2,"sportName":"跑步（22.5km/h）","Calories":757},
        {"num":3,"sportName":"跑步（21km/h）","Calories":652},
        {"num":4,"sportName":"跑步（19.3km/h）","Calories":625},
        {"num":5,"sportName":"跑步（17.7km/h）","Calories":527},
        {"num":6,"sportName":"跑步（16km/h）","Calories":477},
        {"num":7,"sportName":"跑步（12km/h）","Calories":379},
        {"num":8,"sportName":"走路（8km/h）","Calories":273},
        ],
    'liliang': [
        {"num":2,"sportName":"深蹲","Calories":165},
        {"num":3,"sportName":"卷腹","Calories":99},
        {"num":4,"sportName":"仰卧起坐","Calories":99},
        {"num":5,"sportName":"俯卧撑","Calories":99},
        ],
    'qixie': [
        {"num":2,"sportName":"跳绳（22.5km/h）","Calories":757},
        {"num":3,"sportName":"跑步（21km/h）","Calories":652},
        {"num":4,"sportName":"跑步（19.3km/h）","Calories":625},
        {"num":5,"sportName":"跑步（17.7km/h）","Calories":527},
        {"num":6,"sportName":"跑步（16km/h）","Calories":477},
        {"num":7,"sportName":"跑步（12km/h）","Calories":379},
        {"num":8,"sportName":"走路（8km/h）","Calories":273},
        ],
    'qiulei': [
        {"num":2,"sportName":"跳绳（22.5km/h）","Calories":757},
        {"num":3,"sportName":"跑步（21km/h）","Calories":652},
        {"num":4,"sportName":"跑步（19.3km/h）","Calories":625},
        {"num":5,"sportName":"跑步（17.7km/h）","Calories":527},
        {"num":6,"sportName":"跑步（16km/h）","Calories":477},
        {"num":7,"sportName":"跑步（12km/h）","Calories":379},
        {"num":8,"sportName":"走路（8km/h）","Calories":273},
        ],
};